# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(856, 601)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-110, -20, 851, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 35, 10))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 200, 161, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 10, 241, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 350, 241, 111))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("B.G_Template_1.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 430, 101, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Georgia\";\n"
"border-radius: 12px;\n"
"    background-color: rgb(0, 0, 127);\n"
"     color:rgb(255, 255, 255);\n"
"     \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 110, 255);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(580, 200, 131, 101))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("1.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 30, 191, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("jZqDPB.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 300, 161, 121))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("__02-____.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 201, 131))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("f88acab7ffd127b4465659500aa0538f.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 170, 261, 131))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("loading_1.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 320, 231, 151))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Hero_Template.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 430, 101, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Georgia\";\n"
"border-radius: 12px;\n"
"    background-color: rgb(0, 0, 127);\n"
"     color:rgb(255, 255, 255);\n"
"     \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 110, 255);\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.label_2.setText(_translate("JarvisUI", "TextLabel"))
        self.pushButton.setText(_translate("JarvisUI", "START"))
        self.pushButton_2.setText(_translate("JarvisUI", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
